# Generated by Django 3.1.6 on 2021-02-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(default='', upload_to='media/ourwork')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=5000)),
            ],
        ),
    ]
