# Generated by Django 3.1.6 on 2021-02-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InspironHome', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OurWork',
            new_name='service',
        ),
    ]
