# Generated by Django 3.1.7 on 2021-02-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InspironHome', '0002_auto_20210225_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='homebanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(default='', upload_to='media/subservice')),
                ('banner_icon', models.ImageField(default='', upload_to='media/subservice')),
                ('banner_title', models.CharField(max_length=100)),
                ('banner_content', models.CharField(max_length=500)),
            ],
        ),
    ]
