# Generated by Django 3.1.6 on 2021-02-15 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InspironHome', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSubMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Submenu', models.CharField(max_length=50)),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspironHome.service')),
            ],
        ),
    ]
