# Generated by Django 3.1.6 on 2021-02-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InspironHome', '0005_ourwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesubmenu',
            name='Service',
        ),
        migrations.DeleteModel(
            name='service',
        ),
        migrations.DeleteModel(
            name='ServiceSubMenu',
        ),
    ]
