# Generated by Django 3.1.6 on 2021-02-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourwork', '0002_headbanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headbanner',
            name='title',
        ),
    ]
