# Generated by Django 3.1.6 on 2021-02-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourwork', '0004_auto_20210218_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='projectsource1',
            field=models.ImageField(blank=True, upload_to='ourwork/projectsource'),
        ),
        migrations.AlterField(
            model_name='work',
            name='content',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='work',
            name='projectTitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='work',
            name='projecticon',
            field=models.ImageField(blank=True, upload_to='ourwork/projecticon'),
        ),
        migrations.AlterField(
            model_name='work',
            name='projectimage',
            field=models.ImageField(blank=True, upload_to='ourwork/projectimage'),
        ),
        migrations.AlterField(
            model_name='work',
            name='projectsource',
            field=models.ImageField(blank=True, upload_to='ourwork/projectsource'),
        ),
    ]
