# Generated by Django 3.1.6 on 2021-02-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourwork', '0005_auto_20210218_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='projecticon',
            field=models.FileField(blank=True, upload_to='ourwork/projecticon'),
        ),
        migrations.AlterField(
            model_name='work',
            name='projectimage',
            field=models.FileField(blank=True, upload_to='ourwork/projectimage'),
        ),
        migrations.AlterField(
            model_name='work',
            name='projectsource',
            field=models.FileField(blank=True, upload_to='ourwork/projectsource'),
        ),
        migrations.AlterField(
            model_name='work',
            name='projectsource1',
            field=models.FileField(blank=True, upload_to='ourwork/projectsource'),
        ),
    ]
