# Generated by Django 3.1.6 on 2021-02-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourwork', '0006_auto_20210218_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='headbanner',
            name='sourceLink',
            field=models.CharField(default='#', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='sourceLink',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='work',
            name='sourceLink1',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
