# Generated by Django 3.1.6 on 2021-02-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourwork', '0007_auto_20210219_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='headbanner',
            name='projectlink',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='work',
            name='projectlink',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
