# Generated by Django 3.1.6 on 2021-02-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectEnq', models.CharField(max_length=50)),
                ('genralEnq', models.CharField(max_length=50)),
                ('carrerEnq', models.CharField(max_length=50)),
                ('patnershipEnq', models.CharField(max_length=50)),
                ('locationTitle', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('Enq', models.CharField(max_length=50)),
            ],
        ),
    ]
