# Generated by Django 3.1.6 on 2021-02-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourcontact',
            name='location',
            field=models.CharField(max_length=500),
        ),
    ]
