# Generated by Django 3.1.6 on 2021-02-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210219_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('intrest', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=5000)),
            ],
        ),
    ]
