# Generated by Django 3.1.6 on 2021-02-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='owner',
            new_name='owners',
        ),
    ]
