# Generated by Django 3.1.6 on 2021-02-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210219_1433'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
