# Generated by Django 3.1.6 on 2021-02-18 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_expertise_subservices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertise',
            old_name='subservices',
            new_name='services',
        ),
        migrations.AddField(
            model_name='sub_expertise',
            name='services',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
        migrations.AddField(
            model_name='sub_expertise_icon',
            name='services',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
    ]
