# Generated by Django 3.1.6 on 2021-02-18 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20210218_1436'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sub_subservices',
            new_name='service_subcatagory',
        ),
    ]
