# Generated by Django 3.1.6 on 2021-02-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20210218_1448'),
    ]

    operations = [
        migrations.DeleteModel(
            name='service_subcatagory',
        ),
    ]
