# Generated by Django 3.1.6 on 2021-02-18 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20210218_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_serviceweoffer',
            name='services',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
    ]
