# Generated by Django 3.1.6 on 2021-02-18 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_bottomdiv_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_expertise',
            name='subservices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicesubmenu'),
        ),
        migrations.AlterField(
            model_name='sub_expertise_icon',
            name='subservices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicesubmenu'),
        ),
    ]
