# Generated by Django 3.1.6 on 2021-02-18 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_expertisewithtitleicon_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertisewithtitleicon',
            name='subservices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicesubmenu'),
        ),
    ]
