# Generated by Django 3.1.6 on 2021-02-18 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_engagement_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='middleimage',
            name='services',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
    ]
