# Generated by Django 3.1.6 on 2021-02-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_auto_20210218_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_expertise_icon',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
