# Generated by Django 3.1.6 on 2021-02-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_sub_expertise_icon_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_expertise_icon',
            name='icon',
            field=models.FileField(default='', upload_to='media/subexpertise'),
        ),
    ]
